import './globals.css'
import Nav from './UIcomponentes/nav'
import { motion } from 'framer-motion'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Footer from '@/app/components/footer'
import { AOSInit } from './aos'


const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
  title: 'ROYAL AIR MAROC',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">

      <AOSInit />
      <body

        className={`${poppins.className} bg-gray-50`}>

        {children}
        <footer className='mt-11' ><Footer /></footer>
      </body>



    </html>
  )
}
